/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package Currency_Converter;

public class CurrencyConverter extends javax.swing.JFrame {
    double US_Dollar = 1.31;
    double Nigerian_Naira = 476.57;
    double Brazilian_Real = 5.47;
    double Canadian_Dollar = 1.71;
    double Kenyan_Shilling = 132.53;
    double Indonesian_Rupiah = 19554.94;
    double Indian_Rupee = 95.21;
    double Philippine_Pisco = 71.17;
    double Pakistani_Rupee = 162.74;

    String[] currencyUnits = {
            "Units",
            "US Dollar",
            "Nigerian Naira",
            "Brazilian Real",
            "Canadian Dollar",
            "Kenyan Shilling",
            "Indonesian Rupiah",
            "Indian Rupee",
            "Philippine Pisco",
            "Paskistani Rupee"
    };

    /**
     * Creates new form CurrencyConverter
     */
    public CurrencyConverter() {
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.jPanel1 = new javax.swing.JPanel();
        this.jLabel1 = new javax.swing.JLabel();
        this.firstCountry = new javax.swing.JComboBox<>();
        this.secondCountry = new javax.swing.JComboBox<>();
        this.jLabel2 = new javax.swing.JLabel();
        this.jLabel3 = new javax.swing.JLabel();
        this.t1 = new javax.swing.JTextField();
        this.t2 = new javax.swing.JTextField();
        this.jButton1 = new javax.swing.JButton();
        this.jButton2 = new javax.swing.JButton();
        this.jButton3 = new javax.swing.JButton();
        this.secondCurrencyUnit = new javax.swing.JLabel();
        this.firstCurrencyUnit = new javax.swing.JLabel();

        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        this.jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        this.jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        this.jLabel1.setText("Currency Converter");

        this.firstCountry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        this.firstCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One...", "USA",
                "Nigeria", "Brazil", "Canada", "Kenyan", "Indonesia", "India", "Philippine", "Pakistan" }));
        this.firstCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CurrencyConverter.this.firstCountryItemStateChanged(evt);
            }
        });
        this.firstCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrencyConverter.this.firstCountryActionPerformed(evt);
            }
        });

        this.secondCountry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        this.secondCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One...", "USA",
                "Nigeria", "Brazil", "Canada", "Kenyan", "Indonesia", "India", "Philippine", "Pakistan" }));
        this.secondCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CurrencyConverter.this.secondCountryItemStateChanged(evt);
            }
        });

        this.jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        this.jLabel2.setText("From currency Of");

        this.jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        this.jLabel3.setText("To currency Of");

        this.t1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        this.t2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        this.jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        this.jButton1.setText("Convert Currency");
        this.jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrencyConverter.this.jButton1ActionPerformed(evt);
            }
        });

        this.jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        this.jButton2.setText("Reset");
        this.jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrencyConverter.this.jButton2ActionPerformed(evt);
            }
        });

        this.jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        this.jButton3.setText("Exit");
        this.jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrencyConverter.this.jButton3ActionPerformed(evt);
            }
        });

        this.secondCurrencyUnit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        this.secondCurrencyUnit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        this.secondCurrencyUnit.setText("units");

        this.firstCurrencyUnit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        this.firstCurrencyUnit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        this.firstCurrencyUnit.setText("units");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(this.jPanel1);
        this.jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(this.jLabel1)
                                .addGap(290, 290, 290))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(this.jButton1)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(this.firstCountry, 0,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(this.t1)
                                                .addComponent(this.jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(this.firstCurrencyUnit,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(81, 81, 81)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addComponent(this.jLabel3)
                                                                .addComponent(this.secondCountry, 0, 272,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(this.t2))
                                                        .addComponent(this.secondCurrencyUnit,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 277,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(this.jButton2)
                                                .addGap(94, 94, 94)
                                                .addComponent(this.jButton3)))
                                .addContainerGap(114, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(this.jLabel1)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(this.jLabel2)
                                        .addComponent(this.jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(this.firstCountry, javax.swing.GroupLayout.DEFAULT_SIZE, 42,
                                                Short.MAX_VALUE)
                                        .addComponent(this.secondCountry))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(this.t1, javax.swing.GroupLayout.DEFAULT_SIZE, 42,
                                                Short.MAX_VALUE)
                                        .addComponent(this.t2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(this.secondCurrencyUnit,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 20,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(23, 23, 23))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                        .addComponent(this.firstCurrencyUnit,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 20,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(this.jButton1)
                                        .addComponent(this.jButton2)
                                        .addComponent(this.jButton3))
                                .addContainerGap(57, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.getContentPane());
        this.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(this.jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(this.jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        this.pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed

        System.exit(0);

    }// GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed

        this.firstCountry.setSelectedIndex(0);
        this.secondCountry.setSelectedIndex(0);
        this.t1.setText("");
        this.t2.setText("");

    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

        // if(firstCountry.getSelectedIndex()==0 || secondCountry.getSelectedIndex()==0
        // || t1.getText().equals(""))
        // {
        // JOptionPane.showMessageDialog(null,"You Must Select both Countries and must
        // input the amount.","ErrorMessage",
        // JOptionPane.INFORMATION_MESSAGE
        // );
        // return;
        // }

        double amountToChange = Double.parseDouble(this.t1.getText());
        double amountChanged = 0.0;
        double amountInPounds = 0.0;

        switch (this.firstCountry.getSelectedItem().toString()) {
            case "USA":
                amountInPounds = amountToChange / this.US_Dollar;
                break;
            case "Nigeria":
                amountInPounds = amountToChange / this.Nigerian_Naira;
                break;
            case "Brazil":
                amountInPounds = amountToChange / this.Brazilian_Real;
                break;
            case "Canada":
                amountInPounds = amountToChange / this.Canadian_Dollar;
                break;
            case "Kenyan":
                amountInPounds = amountToChange / this.Kenyan_Shilling;
                break;
            case "Indonesia":
                amountInPounds = amountToChange / this.Indonesian_Rupiah;
                break;
            case "India":
                amountInPounds = amountToChange / this.Indian_Rupee;
                break;
            case "Philippine":
                amountInPounds = amountToChange / this.Philippine_Pisco;
                break;
            case "Pakistan":
                amountInPounds = amountToChange / this.Pakistani_Rupee;
                break;
            default:
                amountInPounds = 0.0;
        }

        // amount is Changed in pounds

        switch (this.secondCountry.getSelectedItem().toString()) {
            case "USA":
                amountChanged = amountInPounds * this.US_Dollar;
                break;
            case "Nigeria":
                amountChanged = amountInPounds * this.Nigerian_Naira;
                break;
            case "Brazil":
                amountChanged = amountInPounds * this.Brazilian_Real;
                break;
            case "Canada":
                amountChanged = amountInPounds * this.Canadian_Dollar;
                break;
            case "Kenyan":
                amountChanged = amountInPounds * this.Kenyan_Shilling;
                break;
            case "Indonesia":
                amountChanged = amountInPounds * this.Indonesian_Rupiah;
                break;
            case "India":
                amountChanged = amountInPounds * this.Indian_Rupee;
                break;
            case "Philippine":
                amountChanged = amountInPounds * this.Philippine_Pisco;
                break;
            case "Pakistan":
                amountChanged = amountInPounds * this.Pakistani_Rupee;
                break;
            default:
                amountChanged = amountInPounds * 0.0;
        }

        String value = String.format("%.2f", amountChanged);

        this.t2.setText(value);

    }// GEN-LAST:event_jButton1ActionPerformed

    private void firstCountryActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_firstCountryActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_firstCountryActionPerformed

    private void firstCountryItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_firstCountryItemStateChanged
        this.firstCurrencyUnit.setText(this.currencyUnits[this.firstCountry.getSelectedIndex()]);
    }// GEN-LAST:event_firstCountryItemStateChanged

    private void secondCountryItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_secondCountryItemStateChanged
        this.secondCurrencyUnit.setText(this.currencyUnits[this.secondCountry.getSelectedIndex()]);
    }// GEN-LAST:event_secondCountryItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> firstCountry;
    private javax.swing.JLabel firstCurrencyUnit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> secondCountry;
    private javax.swing.JLabel secondCurrencyUnit;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
